title: BCE
tagline: "The Berkeley Computational Environment: A common compute environment for portable, reproducible data science"
markdown: kramdown
highlighter: pygments
kramdown:
        extensions: ['smart']
gems:
  - jekyll-redirect-from

# This is the default format post.
# For more see: http://jekyllrb.com/docs/permalinks/
# permalink: /:categories/:year/:month/:day/:title

# exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "style.less"]

